SOURCES :=	src_pushswap/main.c \
	src_pushswap/sort.c \
	src_pushswap/sort_functions.c \
	src_pushswap/substack_divide.c \
	src_pushswap/substack_functions.c \
	src_pushswap/substack_sortback.c \
	src_pushswap/substack_split.c \
	src/ilist.c \
	src/nerror.c \
	src/operations/operation_list.c \
	src/operations/operations1.c \
	src/operations/operations2.c \
	src/operations/operations3.c \
	src/program.c \
	src/stack/parse_stack.c \
	src/stack/stack.c \
	src/stack/stack_get.c \
	src/stack/stack_operations.c \
	src/str/ft_atoi.c \
	src/str/ft_split.c \
	src/str/ft_strlen.c \
	src/str/ft_substr.c \
	src/str/str.c \
