SOURCES :=	src_pushswap/main.c \
	src/ft_atoi.c \
	src/ft_split.c \
	src/ft_strlen.c \
	src/ft_substr.c \
	src/ilist.c \
	src/nerror.c \
	src/operation_list.c \
	src/operations1.c \
	src/operations2.c \
	src/operations3.c \
	src/parse_stack.c \
	src/program.c \
	src/sort.c \
	src/sort_functions.c \
	src/stack.c \
	src/stack_get.c \
	src/stack_operations.c \
	src/str.c \
	src/substack_divide.c \
	src/substack_functions.c \
	src/substack_sortback.c \
	src/substack_split.c \
